config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]
  resources :groups, except: [:show] do
    resources :purchases, except: [:show]
  end
  devise_for :users, path: ''

  authenticated :user do
    root "groups#index", as: :groups_path
  end
  root "users#index"  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :read, :all
    can :manage, Group, user: user
    can :manage, Purchase, user: user
    return unless user.admin?

    can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :icon
  has_and_belongs_to_many :purchases
  belongs_to :user
  validates :name, presence: true, length: { minimum: 1 }
  validates :icon, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups
  validates :name, presence: true, length: { minimum: 1 }
  validates :amount, numericality: { greater_than: 0 }
  validates :groups, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :purchases, dependent: :destroy
  has_many :groups, dependent: :destroy
  validates :name, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_url, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[show edit update destroy]
  before_action :set_group, except: %i[destroy create update]

  # GET /purchases or /purchases.json
  def index
    @purchases = @group.purchases
    @total_amount = 0

    @purchases.each do |purchase|
      @total_amount += purchase.amount
    end
  end

  # GET /purchases/new
  def new
    @groups = Group.where(user_id: current_user.id)
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
    @groups = Group.where(user_id: current_user.id)
  end

  # POST /purchases or /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)
    @groups = Group.where(id: groups_params['groups'])
    @purchase.groups << @groups
    @purchase.author = current_user

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to group_purchases_path, notice: 'Purchase was successfully created.' }
        format.json { render :new, status: :created, location: @purchase }
      else
        format.html { redirect_to new_group_purchase_path, alert: 'Failed to create purchase.' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to group_purchases_path, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to group_purchases_path, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_purchase
    @purchase = Purchase.find(params[:id])
    @group = Group.find(params[:group_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  # Only allow a list of trusted parameters through.
  def purchase_params
    params.require(:purchase).permit(:name, :amount)
  end

  def groups_params
    params.require(:purchase).permit(groups: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: @group, class: "d-flex flex-column vh-100 bg-secondary bg-opacity-10" ) do |form| %>
  <div class="navbar d-flex align-items-center bg-main">
    <%= link_to groups_path, class: "btn" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-left text-light" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
      </svg>
    <% end %>
    <p class="navbar-brand m-0 text-light position-absolute top-50 start-50 translate-middle">CATEGORIES</p>
  </div>

  <%= form.text_field :name, autofocus: true, autocomplete: "name", 
    class: "w-100 p-2 mt-3 mb-1", placeholder: "Name"
  %>

  <div class="w-100 p-2 mb-1 bg-white rounded">
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon %>
  </div>

  <div class="w-100 bg-second p-3 mt-auto">
    <%= form.submit "Create Category", class: "w-100 p-3 btn text-light border-light" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="d-flex p-2 bg-white">
  <%= link_to group_purchases_path(group), class: "d-flex" do %>
    <%= image_tag(group.icon, size: "80x80", alt: "Group") %> 

    <div class="ms-3">
      <p>
        Category: 
        <strong><%= group.name %></strong>
      </p>

      <p>
        Total Transactions:
        <strong><%= group.purchases.length %></strong>
      </p>
    </div>
  <% end %>

  <div class="dropdown ms-auto">
    <div class="mt-2" data-bs-toggle="dropdown" aria-expanded="false">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
        <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
      </svg>
    </div>
    <ul class="dropdown-menu">
      <li class="dropdown-item">
        <%= link_to 'Edit', edit_group_path(group) %>
      </li>
      <li class="dropdown-item text-danger">
        <%= link_to 'Delete', group_path(group), data: { turbo_method: :delete } %>
      </li>
    </ul>
  </div>
</div>

app/views/groups/edit.html.erb
<%= render "form", group: @group %>

app/views/groups/index.html.erb
<div class="vh-100 d-flex flex-column bg-secondary bg-opacity-10">
  <div class="navbar d-flex align-items-center justify-content-center bg-main">
    <p class="navbar-brand m-0 text-light">CATEGORIES</p>
  </div>

  <div id="groups">
    <% @groups.each do |group| %>
      <%= link_to group_purchases_path(group) do %>
        <%= render group %>
      <% end %>
    <% end %>
  </div>

  <div class="w-100 bg-second p-3 mt-auto">
    <button class="w-100 p-3 btn text-light border-light">
      <%= link_to "NEW CATEGORY", new_group_path %>
    </button> 
  </div>
</div>

app/views/groups/new.html.erb
<% if @group.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

    <ul>
      <% @group.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render "form", group: @group %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success m-0"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger m-0"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_with(model: [@group, @purchase], class: "d-flex flex-column vh-100 bg-secondary bg-opacity-10") do |form| %>
  <div class="navbar d-flex align-items-center bg-main">
    <%= link_to group_purchases_path, class: "btn" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-left text-light" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
      </svg>
    <% end %>
    <p class="navbar-brand m-0 text-light position-absolute top-50 start-50 translate-middle">PURCHASES</p>
  </div>

  <%= form.text_field :name, autofocus: true, autocomplete: "name", 
    class: "w-100 p-2 mt-3 mb-1", placeholder: "Name"
  %>

  <%= form.number_field :amount, autofocus: true, autocomplete: "amount", 
    class: "w-100 p-2 mt-2 mb-1", placeholder: "Amount $"
  %>

  <div class="p-2 mt-2 bg-white">
    <p> Categories: </p>
    <% @groups.each do |group| %>
      <% @is_checked = group.id == params[:group_id].to_i %>
      <div class="p-2 d-flex align-items-center">
        <%= form.label group.name, class: "w-25" %>
        <%= form.check_box :groups,
          { multiple: true, checked: @is_checked }, group.id, nil
        %>
      </div>
    <% end %>
  </div>


  <div class="w-100 bg-second p-3 mt-auto">
    <%= form.submit "Create Purchase", class: "w-100 p-3 btn text-light border-light" %>
  </div>
<% end %>

app/views/purchases/_purchase.html.erb
<div id="<%= dom_id purchase %>" class="d-flex bg-white p-2 my-2">
  <div>
    <p class="m-0">
      <strong>Name:</strong>
      <%= purchase.name %>
    </p>

    <p class="m-0">
      <strong>Amount:</strong>
      <%= purchase.amount %>
    </p>
  </div>

  <div class="dropdown ms-auto">
    <div class="mt-2" data-bs-toggle="dropdown" aria-expanded="false">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
        <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
      </svg>
    </div>
    <ul class="dropdown-menu">
      <li class="dropdown-item">
        <%= link_to 'Edit', edit_group_purchase_path(group, purchase) %>
      </li>
      <li class="dropdown-item text-danger">
        <%= link_to 'Delete', group_purchase_path(group, purchase), data: { turbo_method: :delete } %>
      </li>
    </ul>
  </div>
</div>

app/views/purchases/edit.html.erb
<%= render "form", group: @group, purchase: @purchase %>

app/views/purchases/index.html.erb
<div class="vh-100 d-flex flex-column bg-secondary bg-opacity-10">
  <div class="navbar d-flex align-items-center bg-main">
    <%= link_to groups_path, class: "btn" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-left text-light" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
      </svg>
    <% end %>
    <p class="navbar-brand m-0 text-light position-absolute top-50 start-50 translate-middle">PURCHASES</p>
  </div>

  <div class="p-2 py-3 bg-white rounded">
    <p class="d-flex align-items-center m-0">
      Total Amount: 
      <strong class="ms-auto">$<%=@total_amount %></strong>
    </p>
  </div>

  <div id="purchases">
    <% @purchases.each do |purchase| %>
      <%= render purchase, group: @group %>
    <% end %>
  </div>

  <div class="w-100 bg-second p-3 mt-auto">
    <button class="w-100 p-3 btn text-light border-light">
      <%= link_to "NEW PURCHASE", new_group_purchase_path %>
    </button> 
  </div>
</div>

app/views/purchases/new.html.erb
<% if @purchase.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this group from being saved:</h2>

    <ul>
      <% @purchase.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [@group, @purchase], class: "d-flex flex-column vh-100 bg-secondary bg-opacity-10") do |form| %>
  <div class="navbar d-flex align-items-center bg-main">
    <%= link_to group_purchases_path, class: "btn" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-left text-light" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
      </svg>
    <% end %>
    <p class="navbar-brand m-0 text-light position-absolute top-50 start-50 translate-middle">PURCHASES</p>
  </div>

  <%= form.text_field :name, autofocus: true, autocomplete: "name", 
    class: "w-100 p-2 mt-3 mb-1", placeholder: "Name"
  %>

  <%= form.number_field :amount, autofocus: true, autocomplete: "amount", 
    class: "w-100 p-2 mt-2 mb-1", placeholder: "Amount $"
  %>

  <div class="p-2 mt-2 bg-white">
    <p> Categories: </p>
    <% @groups.each do |group| %>
      <% @is_checked = group.id == params[:group_id].to_i %>
      <div class="p-2 d-flex align-items-center">
        <%= form.label group.name, class: "w-25" %>
        <%= form.check_box :groups,
          { multiple: true, checked: @is_checked }, group.id, nil
        %>
      </div>
    <% end %>
  </div>


  <div class="w-100 bg-second p-3 mt-auto">
    <%= form.submit "Create Purchase", class: "w-100 p-3 btn text-light border-light" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="p-4 vh-100 d-flex flex-column">
  <h1 class="h-100 d-flex align-items-center justify-content-center">PurchaseTracker</h1>

  <div class="d-flex flex-column gap-2">
    <button class="btn btn-main p-3 fw-semibold">
      <%= link_to 'LOG IN', '/sign_in' %>
    </button>

    <button class="btn p-3 fw-semibold">
      <%= link_to 'SIGN UP', '/sign_up' %>
    </button>
  </div> 
</div>